"""Uses the AST generated by the parser to create a list of instructions in python language.
Usage: python ./compiler.py <source_file> [<output_file>] [-?] [-!] [-no] [--debug-compiler]
    <output_file>: Optional. If provided, the generated code will be saved to this file.
    @option [-?|--help] show help
    @option [-!|--log] log intermediary output using tui
    @option [-no|--no-optimize] don't use accumulator
"""

from io import StringIO, TextIOWrapper
import sys
from functools import partial
from typing import Callable

from utils.istream import InputStream, TuiInputStream
from utils.options import Options
from utils.tui import Tui
from utils.utils import EXIT_ERROR, log, log_error
from modules.lexer import Lexer
from modules.parser import Parser


class CodeGenerator:

    def __init__(self, parser: Parser, logger: Callable = log):
        self.parser = parser
        self._logger = logger

    def start(self):
        program = self.parser.start()
        self.parser._log()  # Final line break
        program.gen(logger=self._logger)


class BufferContainer:
    def __init__(self):
        self.buffer: StringIO | None = None

    def attach(self, buffer: StringIO):
        self.buffer = buffer

    def get_value(self) -> str:
        if self.buffer is None:
            raise ValueError("Buffer is not attached")
        return self.buffer.getvalue()


def main(
    source_filename: str,
    options: int,
    output_file: str = "",
    *args,
    **kwargs,
) -> None | str:
    """
    :param output_file: If provided, the generated code will be saved to the file path.
        Will ignore `is_hybrid_out` and return None.
    :param next: Will forward instructions to run before the Tui be closed.
    """
    if options & Options.LOG:
        tui = Tui(Tui.Mode.CODE_GEN)  # pyright: ignore[reportArgumentType]
        istream: TuiInputStream  # pyright: ignore[reportRedeclaration]
        try:
            istream = TuiInputStream(
                source_filename, partial(tui.log_source, end="")
            )  # pyright: ignore[reportAssignmentType]
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, tui.log_tokens)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            tui.log_ir,
            lambda message, *args, **kwargs: tui.log_debug(
                f"\033[m{message}", *args, **kwargs
            ),
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        code_gen: CodeGenerator
        buffer: StringIO | TextIOWrapper  # pyright: ignore[reportTypeCommentInCode]

        def hybrid_logger(message, *args, end="\n", **kwargs):
            nonlocal buffer
            """Logs to both Tui and a buffer. Used for hybrid/file output mode where Tui is used for intermediary logs, and the final code is saved for later use."""
            tui.log_code(f"{message}", *args, **kwargs)
            buffer.write(
                f"{message}{end}"
            )  # pyright: ignore[reportAttributeAccessIssue]

        if output_file:
            with open(output_file, "w") as f:
                buffer = f
                code_gen = CodeGenerator(
                    parser,
                    hybrid_logger,
                )
                tui.run(
                    code_gen.start,
                    True,
                    not bool(
                        options & Options.NO_EXCEPT_TREATMENT
                    ),  # pyright: ignore[reportCallIssue]
                )
            return None
        else:
            code_gen = CodeGenerator(
                parser,
                logger=partial(tui.log_code, end="\n"),
            )
            tui.run(
                code_gen.start,
                True,
                not bool(
                    options & Options.NO_EXCEPT_TREATMENT
                ),  # pyright: ignore[reportCallIssue]
            )
    else:
        istream: InputStream
        try:
            istream = InputStream(source_filename)
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, lambda *args, **kwargs: None)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            logger=lambda *args, **kwargs: None,
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        code_gen = CodeGenerator(parser)
        code_gen.start()


if __name__ == "__main__":
    import argparse
    from utils.utils import log_warning, log_error, EXIT_SUCCESS, EXIT_ERROR

    parser = argparse.ArgumentParser(
        description="Compiler for your source files.",
        add_help=False  # we'll add custom help options to match original
    )

    # Positional arguments
    parser.add_argument("source", help="Source file to compile")
    parser.add_argument("output", nargs="?", default="", help="Output file (optional)")

    # Option flags (matching original)
    parser.add_argument("-?", "--help", action="help", help="Show this help message and exit")
    parser.add_argument("-!", "--log", action="store_true", help="Enable logging")
    parser.add_argument("-no", "--no-optimize", action="store_true", help="Disable optimizations")
    parser.add_argument("--debug-compiler", action="store_true", help="Disable exception handling for debugging")

    # Parse arguments
    args = parser.parse_args()

    # Build options bitmask
    options = Options.NONE
    if args.log:
        options |= Options.LOG
    if args.no_optimize:
        options |= Options.NO_OPTIMIZE
    if args.debug_compiler:
        options |= Options.NO_EXCEPT_TREATMENT

    # Call main with parsed values
    main(args.source, options, args.output)
