"""Uses the AST generated by the parser to create a list of instructions in python language.
@option [-?|--help] show help
@option [-!|--log] log intermediary output using tui
@option []
"""

from io import StringIO, TextIOWrapper
import sys
from functools import partial
from typing import Callable

from utils.istream import InputStream, TuiInputStream
from utils.options import Options
from utils.tui import Tui
from utils.utils import EXIT_ERROR, log, log_error
from modules.lexer import Lexer
from modules.parser import Parser


class CodeGenerator:

    def __init__(self, parser: Parser, logger: Callable = log):
        self.parser = parser
        self._logger = logger

    def start(self):
        program = self.parser.start()
        self.parser._log()  # Final line break
        program.gen(logger=self._logger)


def main(
    source_filename: str,
    options: int,
    is_hybrid_out: bool = False,
    output_file: str = "",
    *args,
    **kwargs,
) -> None | str:
    """
    :param is_hybrid_out: If True, the function will both log into the output
        panel and return generated code as a string (or `output_file`) for further use.
    :param output_file: If provided, the generated code will be saved to the file path.
        Will ignore `is_hybrid_out` and return None.
    """
    # TODO
    if options & Options.LOG:
        tui = Tui(Tui.Mode.CODE_GEN)
        istream: TuiInputStream  # pyright: ignore[reportRedeclaration]
        try:
            istream = TuiInputStream(
                source_filename, partial(tui.log_source, end="")
            )  # pyright: ignore[reportAssignmentType]
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, tui.log_tokens)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            tui.log_ir,
            lambda message, *args, **kwargs: tui.log_debug(
                f"\033[m{message}", *args, **kwargs
            ),
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        code_gen: CodeGenerator
        buffer: StringIO | TextIOWrapper  # pyright: ignore[reportTypeCommentInCode]

        def hybrid_logger(message, *args, end="\n", **kwargs):
            nonlocal buffer
            """Logs to both Tui and a buffer. Used for hybrid/file output mode where Tui is used for intermediary logs, and the final code is saved for later use."""
            tui.log_code(f"\033[m{message}", *args, **kwargs)
            buffer.write(
                f"{message}{end}"
            )  # pyright: ignore[reportAttributeAccessIssue]

        if output_file:
            with open(output_file, "w") as f:
                buffer = f
                code_gen = CodeGenerator(parser, hybrid_logger)
                tui.run(
                    code_gen.start,
                    True,
                    not bool(
                        options & Options.NO_EXCEPT_TREATMENT
                    ),  # pyright: ignore[reportCallIssue]
                )
            return None
        elif is_hybrid_out:
            buffer = StringIO()
            code_gen = CodeGenerator(parser, logger=hybrid_logger)
            tui.run(
                code_gen.start,
                True,
                not bool(
                    options & Options.NO_EXCEPT_TREATMENT
                ),  # pyright: ignore[reportCallIssue]
            )
            return buffer.getvalue()  # pyright: ignore[reportPossiblyUnboundVariable]
        else:
            code_gen = CodeGenerator(parser, logger=partial(tui.log_code, end="\n"))
            tui.run(
                code_gen.start,
                True,
                not bool(
                    options & Options.NO_EXCEPT_TREATMENT
                ),  # pyright: ignore[reportCallIssue]
            )
    else:
        istream: InputStream
        try:
            istream = InputStream(source_filename)
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, lambda *args, **kwargs: None)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(lexer, optimize=not bool(options & Options.NO_OPTIMIZE))
        code_gen = CodeGenerator(parser)
        code_gen.start()


if __name__ == "__main__":
    from utils.utils import log_warning, EXIT_SUCCESS

    options: int = Options.NONE  # type: ignore
    # Verifica se o usuário passou o nome do arquivo
    if len(sys.argv) < 2:
        log_warning(
            "Uso: \033[32m" "python" f"\033[m {sys.argv[0]} \033[34m<arquivo_fonte>"
        )
        sys.exit(EXIT_ERROR)
    elif len(sys.argv) > 2:
        for i in range(2, len(sys.argv)):
            # TODO -> Grouped options parsing
            if sys.argv[i] in ["-?", "--help"]:
                from ..compiler import show_help

                show_help()
                sys.exit(EXIT_SUCCESS)
            if sys.argv[i] in ["-l", "--lexer"]:
                options |= Options.LEXER
                options |= Options.LOG
            if sys.argv[i] in ["-!", "--log"]:
                options |= Options.LOG
            if sys.argv[i] in ["-no", "--no-optimize"]:
                # Allows the parser to use an accumulator to process results directly
                options |= Options.NO_OPTIMIZE
            if sys.argv[i] in ["--debug-compiler"]:
                options |= Options.NO_EXCEPT_TREATMENT

    main(sys.argv[1], options)
