"""Uses the AST generated by the parser to create a list of instructions in python language.
Usage: python ./compiler.py <source_file> [<output_file>] [-?] [-!] [-no] [--debug-compiler]
    <output_file>: Optional. If provided, the generated code will be saved to this file.
    @option [-?|--help] show help
    @option [-!|--log] log intermediary output using tui
    @option [-no|--no-optimize] don't use accumulator
"""

from io import StringIO, TextIOWrapper
import sys
from functools import partial
from typing import Callable

from ..utils.arg_parser import ArgParser
from ..utils.istream import InputStream, TuiInputStream
from ..utils.options import Options
from ..utils.tui import Tui
from ..utils.utils import EXIT_ERROR, log, log_error
from ..modules.lexer import Lexer
from ..modules.parser import Parser


class CodeGenerator:

    def __init__(self, parser: Parser, logger: Callable = log):
        self.parser = parser
        self._logger = logger

    def start(self):
        program = self.parser.start()
        self.parser._log()  # Final line break
        program.gen(logger=self._logger)


class BufferContainer:
    def __init__(self):
        self.buffer: StringIO | None = None

    def attach(self, buffer: StringIO):
        self.buffer = buffer

    def get_value(self) -> str:
        if self.buffer is None:
            raise ValueError("Buffer is not attached")
        return self.buffer.getvalue()


def parse_append(parser: ArgParser):
    from .parser import parse_append as append

    append(parser)
    # Positional arguments
    parser.add_argument("output", nargs="?", default="", help="Output file (optional)")


def main(
    source_filename: str,
    options: int,
    output_file: str = "",
    *args,
    **kwargs,
) -> None | str:
    """
    :param output_file: If provided, the generated code will be saved to the file path.
        Will ignore `is_hybrid_out` and return None.
    :param next: Will forward instructions to run before the Tui be closed.
    """
    if options & Options.LOG:
        tui = Tui(Tui.Mode.CODE_GEN)  # pyright: ignore[reportArgumentType]
        istream: TuiInputStream  # pyright: ignore[reportRedeclaration]
        try:
            istream = TuiInputStream(
                source_filename, partial(tui.log_source, end="")
            )  # pyright: ignore[reportAssignmentType]
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, tui.log_tokens, source_filename=source_filename)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            tui.log_ir,
            lambda message="", *args, **kwargs: tui.log_debug(
                f"[yellow]Warning {message}[/yellow]", *args, **kwargs
            ),
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        code_gen: CodeGenerator
        buffer: StringIO | TextIOWrapper  # pyright: ignore[reportTypeCommentInCode]

        def hybrid_logger(message, *args, end="\n", **kwargs):
            nonlocal buffer
            """Logs to both Tui and a buffer. Used for hybrid/file output mode where Tui is used for intermediary logs, and the final code is saved for later use."""
            tui.log_code(f"{message}", *args, **kwargs)
            buffer.write(
                f"{message}{end}"
            )  # pyright: ignore[reportAttributeAccessIssue]

        if output_file:
            print(output_file)
            with open(output_file, "w") as f:
                buffer = f
                code_gen = CodeGenerator(
                    parser,
                    hybrid_logger,
                )
                tui.run(
                    code_gen.start,
                    True,
                    not bool(
                        options & Options.NO_EXCEPT_TREATMENT
                    ),  # pyright: ignore[reportCallIssue]
                )
            return
        else:
            code_gen = CodeGenerator(
                parser,
                logger=partial(tui.log_code, end="\n"),
            )
            tui.run(
                code_gen.start,
                True,
                not bool(
                    options & Options.NO_EXCEPT_TREATMENT
                ),  # pyright: ignore[reportCallIssue]
            )
            return
    else:
        istream: InputStream
        try:
            istream = InputStream(source_filename)
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)

        if output_file:
            with open(output_file, "w") as f:
                # Inicializa o lexer + parser com o conteúdo do arquivo
                lexer = Lexer(
                    istream,
                    logger=lambda *args, **kwargs: None,  # Ignora logs
                    source_filename=source_filename,
                )
                parser = Parser(
                    lexer,
                    logger=lambda message="", *args, **kwargs: None,  # Ignora logs
                    optimize=not bool(options & Options.NO_OPTIMIZE),
                )
                code_gen = CodeGenerator(
                    parser,
                    # Usa o arquivo como saída
                    logger=lambda message="", *args, end="\n", **kwargs: f.write(
                        f"{message}{end}"
                    ),
                )
                if options & Options.NO_EXCEPT_TREATMENT:
                    code_gen.start()
                else:
                    try:
                        code_gen.start()
                    except Exception as e:
                        log_error(f"{e}")
            return
        else:
            # Inicializa o lexer + parser com o conteúdo do arquivo
            lexer = Lexer(
                istream, lambda *args, **kwargs: None, source_filename=source_filename
            )
            parser = Parser(
                lexer,
                logger=lambda *args, **kwargs: None,  # Ignora logs
                optimize=not bool(options & Options.NO_OPTIMIZE),
            )
            code_gen = CodeGenerator(parser)
            if options & Options.NO_EXCEPT_TREATMENT:
                code_gen.start()
            else:
                try:
                    code_gen.start()
                except Exception as e:
                    log_error(f"{e}")
            return


if __name__ == "__main__":
    from ..utils.utils import log_error, EXIT_ERROR
    from . import parser as ml_parser

    parser = ArgParser(
        description="Code Generation layer for your MiniLang source files. Fully compiles the MiniLang source to Python code.\n"
        "You need to pass an output file to save the generated code.",
        add_help=False,  # we'll add custom help options to match original
    )

    # Parse arguments
    parse_append(parser)
    args = parser.parse_args()
    options = ml_parser.fetch_options(args)

    # Call main with parsed values
    main(args.source, options, args.output)
