"""Uses the AST generated by the parser to create a list of instructions in python language.
Usage: python ./compiler.py <source_file> [<output_file>] [-?] [-!] [-no] [--debug-compiler]
    <output_file>: Optional. If provided, the generated code will be saved to this file.
    @option [-?|--help] show help
    @option [-!|--log] log intermediary output using tui
    @option [-no|--no-optimize] don't use accumulator
"""

from io import StringIO, TextIOWrapper
import sys
from functools import partial

from ..utils.arg_parser import ArgParser
from ..utils.istream import InputStream, TuiInputStream
from ..utils.options import Options
from ..utils.tui import Tui
from ..utils.utils import EXIT_ERROR, log, log_error
from ..modules.gen import CodeGenerator
from ..modules.lexer import Lexer
from ..modules.parser import Parser


def main(
    source_filename: str,
    options: int,
    output_filename: str = "",
    *args,
    **kwargs,
) -> None | str:
    """
    :param output_filename: If provided, the generated code will be saved to the file path.
        Will ignore `is_hybrid_out` and return None.
    :param next: Will forward instructions to run before the Tui be closed.
    """
    if options & Options.LOG:
        tui = Tui(Tui.Mode.EXECUTION)  # pyright: ignore[reportArgumentType]
        istream: TuiInputStream  # pyright: ignore[reportRedeclaration]
        try:
            istream = TuiInputStream(
                source_filename, partial(tui.log_source, end="")
            )  # pyright: ignore[reportAssignmentType]
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(istream, tui.log_tokens, source_filename=source_filename)
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            tui.log_ir,
            lambda message="", *args, **kwargs: tui.log_debug(
                f"[yellow][b][Warning][/b] {message}[/yellow]", *args, **kwargs
            ),
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        code_gen: CodeGenerator
        buffer: StringIO | TextIOWrapper  # pyright: ignore[reportTypeCommentInCode]

        def hybrid_logger(message, *args, end="\n", **kwargs):
            nonlocal buffer
            """Logs to both Tui and a buffer. Used for hybrid/file output mode where Tui is used for intermediary logs, and the final code is saved for later use."""
            tui.log_code(f"{message}", *args, **kwargs)
            buffer.write(
                f"{message}{end}"
            )  # pyright: ignore[reportAttributeAccessIssue]

        if output_filename:
            try:
                try:
                    buffer = open(output_filename, "w")
                except FileNotFoundError:
                    log_error(f"Error: File '{output_filename}' not found")
                    sys.exit(EXIT_ERROR)
                code_gen = CodeGenerator(
                    parser,
                    hybrid_logger,
                )

                import subprocess

                def run_interpreter1():
                    nonlocal buffer, code_gen, tui
                    code_gen.start()
                    buffer.close()

                    p = subprocess.Popen(
                        f"python {output_filename}",
                        shell=True,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                    )  # pyright: ignore[reportUndefinedVariable]
                    p.wait()
                    stdout, stderr = p.communicate()
                    tui.log_execution(stdout.decode(), end="")
                    tui.log_execution(stderr.decode(), end="\n")
                    # exit(p.returncode)

                tui.run(
                    run_interpreter1,
                    True,
                    not bool(options & Options.NO_EXCEPT_TREATMENT),
                )  # pyright: ignore[reportCallIssue]
            finally:
                if buffer:  # pyright: ignore[reportPossiblyUnboundVariable]
                    buffer.close()
            return None
        else:
            import contextlib

            buffer = StringIO()
            code_gen = CodeGenerator(parser, hybrid_logger)

            def run_interpreter2():
                nonlocal buffer
                code_gen.start()
                code_string = (
                    buffer.getvalue()  # pyright: ignore[reportAttributeAccessIssue]
                )
                stdout_capture = StringIO()
                stderr_capture = StringIO()
                with (
                    contextlib.redirect_stdout(stdout_capture),
                    contextlib.redirect_stderr(stderr_capture),
                ):
                    exec(code_string)  # pyright: ignore[reportPossiblyUnboundVariable]
                tui.log_execution(stdout_capture.getvalue(), end="")
                tui.log_execution(stderr_capture.getvalue(), end="\n")
                exit(EXIT_SUCCESS)

            tui.run(
                run_interpreter2,
                True,
                not bool(
                    options & Options.NO_EXCEPT_TREATMENT
                ),  # pyright: ignore[reportCallIssue]
            )
    else:
        istream: InputStream
        try:
            istream = InputStream(source_filename)
        except FileNotFoundError:
            log_error(f"Error: File '{source_filename}' not found")
            sys.exit(EXIT_ERROR)
        lexer = Lexer(
            istream, lambda *args, **kwargs: None, source_filename=source_filename
        )
        # Inicializa o parser com o conteúdo do arquivo
        parser = Parser(
            lexer,
            logger=lambda *args, **kwargs: None,  # ignora logs
            optimize=not bool(options & Options.NO_OPTIMIZE),
        )
        if output_filename:
            with open(output_filename, "w") as f:
                code_gen = CodeGenerator(
                    parser,
                    lambda message, *args, end="\n", **kwargs: f.write(
                        f"{message}{end}"
                    ),
                )
                code_gen.start()

            import subprocess

            p = subprocess.Popen(
                f"python {output_filename}",
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )  # pyright: ignore[reportUndefinedVariable]
            p.wait()
            stdout, stderr = p.communicate()
            print(stdout.decode(), end="")
            print(stderr.decode(), end="\n")
        else:
            buffer = StringIO()
            code_gen = CodeGenerator(
                parser,
                lambda message, *args, end="\n", **kwargs: buffer.write(
                    f"{message}{end}"
                ),
            )
            code_gen.start()
            code_string = (
                buffer.getvalue()
            )  # pyright: ignore[reportAttributeAccessIssue
            try:
                exec(code_string)  # pyright: ignore[reportUndefinedVariable]
            except Exception as e:
                print(
                    "\033[33m"
                    "Nota: funções recursivas podem dar erro na função `exec` interna do python, usado nesta interpretação. "
                    "Tente executar um arquivo de saída nesses casos!\033[m",
                    file=sys.stderr,
                )

                import traceback

                raise e


if __name__ == "__main__":
    from ..utils.utils import log_error, EXIT_ERROR
    from ..modules import gen
    from ..modules import parser as ml_parser

    parser = ArgParser(
        description="MiniLang interpreter. Uses the gen layer to compile the MiniLang source to Python code, then executes it.\n",
        add_help=False,  # we'll add custom help options to match original
    )
    gen.parse_append(parser)

    # Parse arguments
    args = parser.parse_args()
    options = ml_parser.fetch_options(args)

    # Call main with parsed values
    main(args.source, options, output_filename=args.output)
